### ISSUE TITLE
No trace in Jaeger

### ISSUE THREAD

**Issue by Booster2ooo** [jufab/opentelemetry-angular-interceptor#8]
Hi,

I tried to run the sample example but no trace appears in Jaeger.

As stated in the doc, I did install the npm packages, launched the angular app with ```npm run start:complete-example-app```, [fixed the docker compose config to match v0.4.0](https://github.com/jufab/opentelemetry-angular-interceptor/issues/7) and then launched the containers with docker-compose.

When I visit the app at http://localhost:4200/, everything seems to be working, there is no error in the console, I can see a call to the otelcol endpoint (http://localhost:9090/v1/trace) with a 200/ok response but I don't see anything in Jaeger.

Am I missing something?

**Comment by jufab** [comment]
I tried too with the same fix and i have no problem.
You must have a service "example-app" in Jaeger

<img width="1672" alt="jaeger" src="https://user-images.githubusercontent.com/25395032/87824765-30e17700-c876-11ea-8cc3-753294ddcc55.png">

__docker-compose.yaml__

```yaml
version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - otelcol
    ports:
      - "16686:16686"
      - "14250"
  otel-collector:
    image: otel/opentelemetry-collector:0.4.0
    networks:
      - otelcol
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "9090:9090"
    depends_on:
      - jaeger
networks:
  otelcol:
```

__otel-collector-config.yaml__

```yaml
receivers:
  otlp:
    endpoint: 0.0.0.0:9090
exporters:
  jaeger:
    endpoint: jaeger:14250
    insecure: true
processors:
  batch:
    send_batch_size: 1
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
```
